/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Toggle.h"

int main(void)
{
    led_init();
    switch_init();

    while (1)
    {
        int state = switch_status();

        if (state == 0)        // 1st press
        {
            green_on();
        }
        else if (state == 1)   // 2nd press
        {
            blue_on();
        }
        else if (state == 2)   // 3rd press
        {
            leds_off();
        }
    }
}








